display_name: Nowser
package_name: Nowser

maintainer:
  name: DASHU
  email: haorendashu@gmail.com

priority: optional

section: x11

installed_size: 15700

dependencies:
  - libsqlite3-0
  - libsqlite3-dev
  - libsecret-1-dev

essential: false

icon: assets/imgs/logo/logo512.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - Nostr
  - Nostr Client

generic_name: Nostr Client

categories:
  - Network

startup_notify: true